<action>
    <id>addSlotLocation</id>
    <name>Add_Slot_Location</name>
    <description>Add a slot location</description>
     
    <type>ADD</type>
 
    <ws>
        <method>POST</method>
        <href>/slotLocations</href>
    </ws>
    <impl>
        <command>create slot location</command>
    </impl>
    <auth>
        <opt>optOpen</opt>
    </auth>
    <primary>true</primary>
</action>